version: '2'

services:
  app:
    build:
      context: .
    image: {{ cookiecutter.docker_org }}/{{ cookiecutter.project_name }}
    depends_on:
    - psql
    links:
    - psql
    environment:
      DATABASE_URL: postgres://postgres:@psql/postgres
  psql:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: ''
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql

volumes:
  pg_data:
    driver: local

